apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      imagePullSecrets:
      - name: gar-secret
      containers:
      - name: simple-app
        image: us-central1-docker.pkg.dev/poc-070424/k3s-repo/simple-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
