name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: poc-070424

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=us-central1-docker.pkg.dev/poc-070424/my-repo/my-app:$GITHUB_SHA
        docker build -t $IMAGE_TAG .
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push $IMAGE_TAG

    - name: Deploy to Cloud Run
      run: |
        pwd
        ls -lrt
        gcloud run deploy my-cloud-run-service \
          --image $IMAGE_TAG \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
